// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeSeries.Infrastructure;

#nullable disable

namespace TimeSeries.Infrastructure.Migrations
{
    [DbContext(typeof(TimeSeriesDbContext))]
    [Migration("20260722143903_CreateTimeSeriesTables")]
    partial class CreateTimeSeriesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeSeries.Domain.ProcessingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageValue")
                        .HasColumnType("double precision");

                    b.Property<double>("DateDeltaSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("FirstOperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UploadedFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AverageExecutionTime");

                    b.HasIndex("AverageValue");

                    b.HasIndex("FirstOperationDate");

                    b.HasIndex("UploadedFileId")
                        .IsUnique();

                    b.ToTable("ProcessingResults");
                });

            modelBuilder.Entity("TimeSeries.Domain.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("NormalizedFileName")
                        .IsUnique();

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("TimeSeries.Domain.Value", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<double>("IndicatorValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UploadedFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedFileId", "Date");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("TimeSeries.Domain.ProcessingResult", b =>
                {
                    b.HasOne("TimeSeries.Domain.UploadedFile", "UploadedFile")
                        .WithOne("ProcessingResult")
                        .HasForeignKey("TimeSeries.Domain.ProcessingResult", "UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("TimeSeries.Domain.Value", b =>
                {
                    b.HasOne("TimeSeries.Domain.UploadedFile", "UploadedFile")
                        .WithMany("Values")
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("TimeSeries.Domain.UploadedFile", b =>
                {
                    b.Navigation("ProcessingResult")
                        .IsRequired();

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
